//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soujiwolf.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broadcast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Broadcast()
        {
            this.BroadcastListeners = new HashSet<BroadcastListener>();
        }
    
        public System.Guid BroadcastId { get; set; }
        public long GuildSnowflake { get; set; }
        public long ChannelSnowflake { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BroadcastListener> BroadcastListeners { get; set; }
    }
}
