//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soujiwolf.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BroadcastListener
    {
        public long GuildSnowflake { get; set; }
        public long ChannelSnowflake { get; set; }
        public System.Guid BroadcastBroadcastId { get; set; }
        public long BroadcastGuildSnowflake { get; set; }
        public long BroadcastChannelSnowflake { get; set; }
    
        public virtual Broadcast Broadcast { get; set; }
    }
}
