//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soujiwolf.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoujiwolfConnection : DbContext
    {
        public SoujiwolfConnection()
            : base("name=SoujiwolfConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ModeratorRole> ModeratorRoles { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
        public virtual DbSet<Werewolf> WerewolfGame { get; set; }
        public virtual DbSet<GameRole> GameRoles { get; set; }
        public virtual DbSet<PlayerRole> PlayerRoles { get; set; }
        public virtual DbSet<Broadcast> Broadcasts { get; set; }
        public virtual DbSet<BroadcastListener> BroadcastListeners { get; set; }
    }
}
