//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soujiwolf.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Werewolf
    {
        public long GuildSnowflake { get; set; }
        public long PlayerRoleSnowflake { get; set; }
        public long NarratorRoleSnowflake { get; set; }
        public long VillageChannelSnowflake { get; set; }
        public long WerewolfChannelSnowflake { get; set; }
        public string Status { get; set; }
        public long DeadRoleSnowflake { get; set; }
    }
}
